/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mara ruiz
 */
public class frmayuda extends javax.swing.JPanel {

    /**
     * Creates new form panel2
     */
    public frmayuda() {
        initComponents();
        ocultar();
        
    }
     public void ocultar(){
        
        need2.setVisible(false);
        need3.setVisible(false);
        need4.setVisible(false);
       
       

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        need4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        reservas = new javax.swing.JButton();
        consumos = new javax.swing.JButton();
        pagos = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        p1 = new javax.swing.JButton();
        parchivos = new javax.swing.JButton();
        reserva = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        need2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        need3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        productos = new javax.swing.JButton();
        habitaciones = new javax.swing.JButton();
        need1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel38 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(10, 19, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        need4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(29, 169, 124));
        jLabel17.setText("Reservas");
        jLabel17.setOpaque(true);

        reservas.setBackground(new java.awt.Color(255, 255, 255));
        reservas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reservas.setForeground(new java.awt.Color(0, 51, 153));
        reservas.setText("Gestion Reservas");
        reservas.setBorder(null);
        reservas.setBorderPainted(false);
        reservas.setContentAreaFilled(false);
        reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservas.setFocusPainted(false);
        reservas.setOpaque(true);
        reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasMouseClicked(evt);
            }
        });
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });

        consumos.setBackground(new java.awt.Color(255, 255, 255));
        consumos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        consumos.setForeground(new java.awt.Color(0, 51, 153));
        consumos.setText("Gestion Consumos");
        consumos.setBorder(null);
        consumos.setBorderPainted(false);
        consumos.setContentAreaFilled(false);
        consumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consumos.setFocusPainted(false);
        consumos.setOpaque(true);
        consumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consumosMouseClicked(evt);
            }
        });
        consumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumosActionPerformed(evt);
            }
        });

        pagos.setBackground(new java.awt.Color(255, 255, 255));
        pagos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pagos.setForeground(new java.awt.Color(0, 51, 153));
        pagos.setText("Gestion Pagos");
        pagos.setBorder(null);
        pagos.setBorderPainted(false);
        pagos.setContentAreaFilled(false);
        pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagos.setFocusPainted(false);
        pagos.setOpaque(true);
        pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagosMouseClicked(evt);
            }
        });
        pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagosActionPerformed(evt);
            }
        });

        clientes.setBackground(new java.awt.Color(255, 255, 255));
        clientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clientes.setForeground(new java.awt.Color(0, 51, 153));
        clientes.setText("Gestion Clientes");
        clientes.setBorder(null);
        clientes.setBorderPainted(false);
        clientes.setContentAreaFilled(false);
        clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientes.setFocusPainted(false);
        clientes.setOpaque(true);
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
        });
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout need4Layout = new javax.swing.GroupLayout(need4);
        need4.setLayout(need4Layout);
        need4Layout.setHorizontalGroup(
            need4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(need4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientes)
                    .addComponent(pagos)
                    .addComponent(consumos)
                    .addComponent(reservas)
                    .addComponent(jLabel17))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        need4Layout.setVerticalGroup(
            need4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(reservas)
                .addGap(18, 18, 18)
                .addComponent(consumos)
                .addGap(18, 18, 18)
                .addComponent(pagos)
                .addGap(18, 18, 18)
                .addComponent(clientes)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        add(need4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 610, 370));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ereserva.png"))); // NOI18N
        p1.setBorder(null);
        p1.setBorderPainted(false);
        p1.setContentAreaFilled(false);
        p1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p1.setFocusPainted(false);
        p1.setSelected(true);
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1MouseExited(evt);
            }
        });

        parchivos.setBackground(new java.awt.Color(10, 19, 51));
        parchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Earchivo.png"))); // NOI18N
        parchivos.setBorder(null);
        parchivos.setBorderPainted(false);
        parchivos.setContentAreaFilled(false);
        parchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parchivos.setFocusPainted(false);
        parchivos.setSelected(true);
        parchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parchivosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                parchivosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                parchivosMouseExited(evt);
            }
        });
        parchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parchivosActionPerformed(evt);
            }
        });

        reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eengranage.png"))); // NOI18N
        reserva.setBorder(null);
        reserva.setBorderPainted(false);
        reserva.setContentAreaFilled(false);
        reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserva.setFocusPainted(false);
        reserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reserva.setSelected(true);
        reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservaMouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Configuraciones");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Reservas");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Archivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(reserva)))
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(parchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 0, 615, 110));

        need2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 169, 124));
        jLabel15.setText("Configuraciones");
        jLabel15.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Gestion Empleados");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout need2Layout = new javax.swing.GroupLayout(need2);
        need2.setLayout(need2Layout);
        need2Layout.setHorizontalGroup(
            need2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(need2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel15))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        need2Layout.setVerticalGroup(
            need2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        add(need2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 610, 370));

        need3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(29, 169, 124));
        jLabel16.setText("Archivo");
        jLabel16.setOpaque(true);

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productos.setForeground(new java.awt.Color(0, 51, 153));
        productos.setText("Gestion Productos");
        productos.setBorder(null);
        productos.setBorderPainted(false);
        productos.setContentAreaFilled(false);
        productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productos.setFocusPainted(false);
        productos.setOpaque(true);
        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosMouseClicked(evt);
            }
        });
        productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosActionPerformed(evt);
            }
        });

        habitaciones.setBackground(new java.awt.Color(255, 255, 255));
        habitaciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        habitaciones.setForeground(new java.awt.Color(0, 51, 153));
        habitaciones.setText("Gestion Habitaciones");
        habitaciones.setBorder(null);
        habitaciones.setBorderPainted(false);
        habitaciones.setContentAreaFilled(false);
        habitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habitaciones.setFocusPainted(false);
        habitaciones.setOpaque(true);
        habitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habitacionesMouseClicked(evt);
            }
        });
        habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout need3Layout = new javax.swing.GroupLayout(need3);
        need3.setLayout(need3Layout);
        need3Layout.setHorizontalGroup(
            need3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(need3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitaciones)
                    .addComponent(productos)
                    .addComponent(jLabel16))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        need3Layout.setVerticalGroup(
            need3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addComponent(productos)
                .addGap(18, 18, 18)
                .addComponent(habitaciones)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        add(need3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 610, 370));

        need1.setBackground(new java.awt.Color(13, 37, 63));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/duda2.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(142, 137, 171));
        jLabel38.setText("No haz seleccionado ningun icono");

        javax.swing.GroupLayout need1Layout = new javax.swing.GroupLayout(need1);
        need1.setLayout(need1Layout);
        need1Layout.setHorizontalGroup(
            need1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need1Layout.createSequentialGroup()
                .addGroup(need1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(need1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel38))
                    .addGroup(need1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        need1Layout.setVerticalGroup(
            need1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(need1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel38))
        );

        add(need1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 620, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void p1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseEntered

    }//GEN-LAST:event_p1MouseEntered

    private void p1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseExited

    }//GEN-LAST:event_p1MouseExited

    private void parchivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parchivosMouseEntered
        

    }//GEN-LAST:event_parchivosMouseEntered

    private void parchivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parchivosMouseExited
        
    }//GEN-LAST:event_parchivosMouseExited

    private void parchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parchivosActionPerformed

    private void reservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseEntered
       
    }//GEN-LAST:event_reservaMouseEntered

    private void reservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseExited
       
    }//GEN-LAST:event_reservaMouseExited

    private void reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseClicked
        need1.setVisible(false);
        need2.setVisible(true);
        need3.setVisible(false);
        need4.setVisible(false);
    }//GEN-LAST:event_reservaMouseClicked

    private void parchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parchivosMouseClicked
        need1.setVisible(false);
        need2.setVisible(false);
        need3.setVisible(true);
        need4.setVisible(false);
    }//GEN-LAST:event_parchivosMouseClicked

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        need1.setVisible(false);
        need2.setVisible(false);
        need3.setVisible(false);
        need4.setVisible(true);
    }//GEN-LAST:event_p1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//asdas        
        
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\empleados.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseClicked
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\productos.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productosMouseClicked

    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosActionPerformed

    private void habitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habitacionesMouseClicked
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\habitaciones.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_habitacionesMouseClicked

    private void habitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionesActionPerformed

    private void reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasMouseClicked
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\reservas.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reservasMouseClicked

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservasActionPerformed

    private void consumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consumosMouseClicked
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\consumos.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consumosMouseClicked

    private void consumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumosActionPerformed

    private void pagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagosMouseClicked
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\pagos.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pagosMouseClicked

    private void pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagosActionPerformed

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Christian\\Desktop\\Universidad\\Cuarto semestre\\Ingeniería de software\\Proyecto Final Definitivo\\ProyectoFinal\\SistemaReservacionHotel\\src\\Files\\clientes.pdf";
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
             p.start();
        } catch (IOException ex) {
            Logger.getLogger(frmayuda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clientesMouseClicked

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientes;
    private javax.swing.JButton consumos;
    private javax.swing.JButton habitaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel need1;
    private javax.swing.JPanel need2;
    private javax.swing.JPanel need3;
    private javax.swing.JPanel need4;
    private javax.swing.JButton p1;
    private javax.swing.JButton pagos;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JButton parchivos;
    private javax.swing.JButton productos;
    private javax.swing.JButton reserva;
    private javax.swing.JButton reservas;
    // End of variables declaration//GEN-END:variables
}
