/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author mara ruiz
 */
public class frmacceso extends javax.swing.JPanel {

    /**
     * Creates new form panel5
     */
    public frmacceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblapaterno = new javax.swing.JLabel();
        lblamaterno = new javax.swing.JLabel();
        lblacceso = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblidpersona = new javax.swing.JLabel();
        instagram1 = new javax.swing.JButton();
        instagram = new javax.swing.JButton();
        instagram2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(10, 19, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnombre.setText("nombre");

        lblapaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblapaterno.setText("apellido paterno");

        lblamaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblamaterno.setText("apellido materno");

        lblacceso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblacceso.setText("ID");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nombres");
        jLabel12.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Apellidos");
        jLabel14.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Tipo de acceso");
        jLabel16.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("ID");
        jLabel13.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 169, 124));
        jLabel15.setText("Datos del usuario");
        jLabel15.setOpaque(true);

        lblidpersona.setText("Identificador");

        instagram1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonfacebook.png"))); // NOI18N
        instagram1.setBorder(null);
        instagram1.setBorderPainted(false);
        instagram1.setContentAreaFilled(false);
        instagram1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram1.setFocusPainted(false);
        instagram1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonfacebook2.png"))); // NOI18N
        instagram1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonfacebook2.png"))); // NOI18N
        instagram1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonfacebook2.png"))); // NOI18N
        instagram1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagram1MouseClicked(evt);
            }
        });

        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInstagram.png"))); // NOI18N
        instagram.setBorder(null);
        instagram.setBorderPainted(false);
        instagram.setContentAreaFilled(false);
        instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram.setFocusPainted(false);
        instagram.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInstagram2.png"))); // NOI18N
        instagram.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInstagram2.png"))); // NOI18N
        instagram.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInstagram2.png"))); // NOI18N
        instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramMouseClicked(evt);
            }
        });

        instagram2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botontwitter.png"))); // NOI18N
        instagram2.setBorder(null);
        instagram2.setBorderPainted(false);
        instagram2.setContentAreaFilled(false);
        instagram2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram2.setFocusPainted(false);
        instagram2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botontwitter2.png"))); // NOI18N
        instagram2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botontwitter2.png"))); // NOI18N
        instagram2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botontwitter2.png"))); // NOI18N
        instagram2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagram2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel15)
                .addGap(0, 298, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidpersona)
                    .addComponent(lblamaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblapaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblacceso)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instagram1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instagram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instagram2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(instagram, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instagram1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instagram2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblidpersona)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblnombre)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel14)
                                .addGap(8, 8, 8)
                                .addComponent(lblapaterno)
                                .addGap(3, 3, 3)
                                .addComponent(lblamaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblacceso)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramMouseClicked
        try{
            Desktop.getDesktop().browse(URI.create("https://www.instagram.com/oneyonly4ya/"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_instagramMouseClicked

    private void instagram1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagram1MouseClicked
        try{
            Desktop.getDesktop().browse(URI.create("https://www.facebook.com/OneOnly-104837647907320/"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_instagram1MouseClicked

    private void instagram2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagram2MouseClicked
        try{
            Desktop.getDesktop().browse(URI.create("https://twitter.com/OneOnly94131064"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_instagram2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton instagram;
    private javax.swing.JButton instagram1;
    private javax.swing.JButton instagram2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblacceso;
    public static javax.swing.JLabel lblamaterno;
    public static javax.swing.JLabel lblapaterno;
    public static javax.swing.JLabel lblidpersona;
    public static javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables
}
