/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Vhabitacion;
import Logica.Fhabitacion;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author mara ruiz
 */
public class frminicio extends javax.swing.JFrame implements ActionListener{

    frmtrabajador panel1 =new frmtrabajador();
    frmreserva panel3 = new frmreserva();
    frmayuda panel2 =new frmayuda();
    frmhabitacion panel4 = new frmhabitacion();
    frmacceso panel5 =new frmacceso();
    frmproducto panel6 = new frmproducto();
    frmcliente panel7 =new frmcliente();
   
    public frminicio() {
        initComponents();
        ocultar();
        Contenedor.add(panel5);
        pconfiguracion.addActionListener(this);
        p2.addActionListener(this);
        p3.addActionListener(this);
        p4.addActionListener(this);
        p5.addActionListener(this);
        p6.addActionListener(this);
        p7.addActionListener(this);
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(1042, 700));
        this.setMinimumSize(new Dimension(1042, 700));
        
       try{
        setIconImage(new ImageIcon(getClass().getResource("/img/internet12.png")).getImage());
        }
        catch(Exception E){
            
        }
       setTitle("One&Only");
        
    }
        public void ocultar(){
        
        Preservas.setVisible(false);
        Parchivo.setVisible(false);
        aGuardar.setVisible(false);
        titulo.setVisible(false);
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Parchivo = new javax.swing.JPanel();
        p4 = new javax.swing.JButton();
        p6 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();
        parchivos = new javax.swing.JButton();
        salida = new javax.swing.JButton();
        reserva = new javax.swing.JButton();
        Preservas = new javax.swing.JPanel();
        p3 = new javax.swing.JButton();
        p7 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        pconfiguracion = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        aGuardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContenedorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ContenedorMouseReleased(evt);
            }
        });
        Contenedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ContenedorMouseDragged(evt);
            }
        });
        Contenedor.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(10, 19, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Parchivo.setLayout(new java.awt.GridLayout(0, 1));

        p4.setBackground(new java.awt.Color(255, 255, 255));
        p4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p4.setForeground(new java.awt.Color(102, 102, 102));
        p4.setText("Habitaciones");
        p4.setBorder(null);
        p4.setBorderPainted(false);
        p4.setContentAreaFilled(false);
        p4.setFocusPainted(false);
        p4.setOpaque(true);
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p4MouseExited(evt);
            }
        });
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });
        Parchivo.add(p4);

        p6.setBackground(new java.awt.Color(255, 255, 255));
        p6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p6.setForeground(new java.awt.Color(102, 102, 102));
        p6.setText("Productos");
        p6.setBorder(null);
        p6.setBorderPainted(false);
        p6.setContentAreaFilled(false);
        p6.setFocusPainted(false);
        p6.setOpaque(true);
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p6MouseExited(evt);
            }
        });
        Parchivo.add(p6);

        jPanel2.add(Parchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 69, 130, 50));

        p5.setBackground(new java.awt.Color(10, 19, 51));
        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luna4.png"))); // NOI18N
        p5.setBorder(null);
        p5.setBorderPainted(false);
        p5.setContentAreaFilled(false);
        p5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p5.setFocusPainted(false);
        p5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luna3.png"))); // NOI18N
        p5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luna3.png"))); // NOI18N
        p5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luna3.png"))); // NOI18N
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p5MouseExited(evt);
            }
        });
        jPanel2.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        parchivos.setBackground(new java.awt.Color(10, 19, 51));
        parchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo2.png"))); // NOI18N
        parchivos.setBorder(null);
        parchivos.setBorderPainted(false);
        parchivos.setContentAreaFilled(false);
        parchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parchivos.setFocusPainted(false);
        parchivos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo.png"))); // NOI18N
        parchivos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo.png"))); // NOI18N
        parchivos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo.png"))); // NOI18N
        parchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parchivosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                parchivosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                parchivosMouseExited(evt);
            }
        });
        parchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parchivosActionPerformed(evt);
            }
        });
        jPanel2.add(parchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 60, 80));

        salida.setBackground(new java.awt.Color(10, 19, 51));
        salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/senales2.png"))); // NOI18N
        salida.setBorder(null);
        salida.setBorderPainted(false);
        salida.setContentAreaFilled(false);
        salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salida.setFocusPainted(false);
        salida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/senales.png"))); // NOI18N
        salida.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/senales.png"))); // NOI18N
        salida.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/senales.png"))); // NOI18N
        salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidaMouseClicked(evt);
            }
        });
        jPanel2.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 50, 50));

        reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reserva2.png"))); // NOI18N
        reserva.setBorder(null);
        reserva.setBorderPainted(false);
        reserva.setContentAreaFilled(false);
        reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserva.setFocusPainted(false);
        reserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reserva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reserva.png"))); // NOI18N
        reserva.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reserva.png"))); // NOI18N
        reserva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reserva.png"))); // NOI18N
        reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservaMouseExited(evt);
            }
        });
        reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaActionPerformed(evt);
            }
        });
        jPanel2.add(reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 70, 80));

        Preservas.setBackground(new java.awt.Color(51, 51, 51));
        Preservas.setMinimumSize(new java.awt.Dimension(89, 34));
        Preservas.setPreferredSize(new java.awt.Dimension(100, 43));
        Preservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PreservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PreservasMouseExited(evt);
            }
        });
        Preservas.setLayout(new java.awt.GridLayout(0, 1));

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p3.setForeground(new java.awt.Color(102, 102, 102));
        p3.setText("Reservas y Consumos");
        p3.setBorder(null);
        p3.setBorderPainted(false);
        p3.setContentAreaFilled(false);
        p3.setFocusPainted(false);
        p3.setOpaque(true);
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p3MouseExited(evt);
            }
        });
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });
        p3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p3FocusGained(evt);
            }
        });
        Preservas.add(p3);

        p7.setBackground(new java.awt.Color(255, 255, 255));
        p7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p7.setForeground(new java.awt.Color(102, 102, 102));
        p7.setText("Clientes");
        p7.setBorder(null);
        p7.setBorderPainted(false);
        p7.setContentAreaFilled(false);
        p7.setFocusPainted(false);
        p7.setOpaque(true);
        p7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p7MouseExited(evt);
            }
        });
        Preservas.add(p7);

        jPanel2.add(Preservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 71, 160, 50));

        p2.setBackground(new java.awt.Color(10, 19, 51));
        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pregunta2.png"))); // NOI18N
        p2.setBorder(null);
        p2.setBorderPainted(false);
        p2.setContentAreaFilled(false);
        p2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p2.setFocusPainted(false);
        p2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pregunta.png"))); // NOI18N
        p2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pregunta.png"))); // NOI18N
        p2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pregunta.png"))); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 60, 70));

        pconfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engranaje2.png"))); // NOI18N
        pconfiguracion.setBorder(null);
        pconfiguracion.setBorderPainted(false);
        pconfiguracion.setContentAreaFilled(false);
        pconfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pconfiguracion.setFocusPainted(false);
        pconfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engranaje.png"))); // NOI18N
        pconfiguracion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engranaje.png"))); // NOI18N
        pconfiguracion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engranaje.png"))); // NOI18N
        pconfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pconfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pconfiguracionMouseExited(evt);
            }
        });
        jPanel2.add(pconfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 80));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1040, 10));

        aGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aGuardar.setForeground(new java.awt.Color(102, 102, 102));
        aGuardar.setText("One & Only");
        aGuardar.setOpaque(true);
        jPanel2.add(aGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 20));

        Contenedor.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(Contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parchivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parchivosMouseEntered
        
        
    }//GEN-LAST:event_parchivosMouseEntered

    private void parchivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parchivosMouseExited
        Parchivo.setVisible(false);
    }//GEN-LAST:event_parchivosMouseExited

    private void parchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parchivosActionPerformed

    private void p4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseEntered
     
        Parchivo.setVisible(true);
        p4.setBackground(new java.awt.Color(195, 196, 201));
        
        
    }//GEN-LAST:event_p4MouseEntered

    private void p4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseExited
   
        Parchivo.setVisible(false);
        p4.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_p4MouseExited

    private void p6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseEntered
        Parchivo.setVisible(true);
        p6.setBackground(new java.awt.Color(195, 196, 201));
    }//GEN-LAST:event_p6MouseEntered

    private void p6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseExited
        Parchivo.setVisible(false);
        p6.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_p6MouseExited

    private void salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salidaMouseClicked

    private void reservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseEntered
        
    }//GEN-LAST:event_reservaMouseEntered

    private void reservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseExited
        Preservas.setVisible(false);
    }//GEN-LAST:event_reservaMouseExited

    private void p3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p3FocusGained

    }//GEN-LAST:event_p3FocusGained

    private void p3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseEntered
        
        Preservas.setVisible(true);
        p3.setBackground(new java.awt.Color(195, 196, 201));
    }//GEN-LAST:event_p3MouseEntered

    private void p3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseExited
        Preservas.setVisible(false);
        p3.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_p3MouseExited

    private void p7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseEntered
        Preservas.setVisible(true);
        p7.setBackground(new java.awt.Color(195, 196, 201));
    }//GEN-LAST:event_p7MouseEntered

    private void p7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseExited
        Preservas.setVisible(false);
        p7.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_p7MouseExited

    private void PreservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreservasMouseEntered
        Preservas.setVisible(true);
    }//GEN-LAST:event_PreservasMouseEntered

    private void PreservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreservasMouseExited
        Preservas.setVisible(false);
    }//GEN-LAST:event_PreservasMouseExited

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void pconfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconfiguracionMouseEntered
       
    }//GEN-LAST:event_pconfiguracionMouseEntered

    private void pconfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconfiguracionMouseExited
       
    }//GEN-LAST:event_pconfiguracionMouseExited

    private void p5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseEntered
        aGuardar.setVisible(true);
    }//GEN-LAST:event_p5MouseEntered

    private void p5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseExited
        aGuardar.setVisible(false);
    }//GEN-LAST:event_p5MouseExited
int xx,xy;
    private void ContenedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorMousePressed
        setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_ContenedorMousePressed

    private void ContenedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_ContenedorMouseReleased

    private void ContenedorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_ContenedorMouseDragged

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3ActionPerformed

    private void parchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parchivosMouseClicked
        // TODO add your handling code here:
        Parchivo.setVisible(true);
    }//GEN-LAST:event_parchivosMouseClicked

    private void reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseClicked
        // TODO add your handling code here:
        Preservas.setVisible(true);
    }//GEN-LAST:event_reservaMouseClicked

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
        //panel4.update(null);
    }//GEN-LAST:event_p4ActionPerformed

    private void reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frminicio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Parchivo;
    private javax.swing.JPanel Preservas;
    private javax.swing.JLabel aGuardar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton p2;
    private javax.swing.JButton p3;
    public static javax.swing.JButton p4;
    private javax.swing.JButton p5;
    public static javax.swing.JButton p6;
    private javax.swing.JButton p7;
    public static javax.swing.JButton parchivos;
    public static javax.swing.JButton pconfiguracion;
    private javax.swing.JButton reserva;
    private javax.swing.JButton salida;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       Object evt = e.getSource();
       if(evt.equals(pconfiguracion)){
           titulo.setText("Trabajadores");
           titulo.setVisible(true);
           panel2.setVisible(false);
           panel3.setVisible(false);
           panel4.setVisible(false);
           panel5.setVisible(false);
           panel1.setVisible(true);
           panel6.setVisible(false);
           panel7.setVisible(false);
           Contenedor.add(panel1);
           Contenedor.validate();
       }
       else if(evt.equals(p2)){
           titulo.setText("Ayuda");
           titulo.setVisible(true);
           panel2.setVisible(true);
           panel1.setVisible(false);
           panel3.setVisible(false);
           panel4.setVisible(false);
           panel5.setVisible(false);
           panel6.setVisible(false);
           panel7.setVisible(false);
           Contenedor.add(panel2);
           Contenedor.validate();
       }
       else if(evt.equals(p3)){
           titulo.setText("Reservas");
           titulo.setVisible(true);
           panel1.setVisible(false);
           panel2.setVisible(false);
           panel3.setVisible(true);
           panel4.setVisible(false);
           panel5.setVisible(false);
           panel6.setVisible(false);
           panel7.setVisible(false);
           Contenedor.add(panel3);
           Contenedor.validate();
       }
       else if(evt.equals(p4)){
           titulo.setText("Habitaciones");
           titulo.setVisible(true);
           panel1.setVisible(false);
           panel2.setVisible(false);
           panel3.setVisible(false);
           panel4.setVisible(true);
           panel5.setVisible(false);
           panel6.setVisible(false);
           panel7.setVisible(false);
           Contenedor.add(panel4);
           Contenedor.validate();
       }
       else if(evt.equals(p5)){
           titulo.setVisible(false);
           panel1.setVisible(false);
           panel2.setVisible(false);
           panel3.setVisible(false);
           panel4.setVisible(false);
           panel5.setVisible(true);
           panel6.setVisible(false);
           panel7.setVisible(false);
           Contenedor.add(panel5);
           Contenedor.validate();
       }
       else if(evt.equals(p6)){
           titulo.setText("Productos");
           titulo.setVisible(true);
           panel1.setVisible(false);
           panel2.setVisible(false);
           panel3.setVisible(false);
           panel4.setVisible(false);
           panel5.setVisible(false);
           panel6.setVisible(true);
           panel7.setVisible(false);
           Contenedor.add(panel6);
           Contenedor.validate();
       }
       else if(evt.equals(p7)){
           titulo.setText("Clientes");
           titulo.setVisible(true);
           panel1.setVisible(false);
           panel2.setVisible(false);
           panel3.setVisible(false);
           panel4.setVisible(false);
           panel5.setVisible(false);
           panel6.setVisible(false);
           panel7.setVisible(true);
           Contenedor.add(panel7);
           Contenedor.validate();
       }
    }
}
